# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: emoji-extractor 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "emoji-extractor"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Andrey Cherkashin", "Aman Gupta"]
  s.date = "2014-08-05"
  s.description = "extracts high-resolution emoji pngs from ttf"
  s.email = "with.out@me.com"
  s.executables = ["emoji-extractor"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/emoji-extractor",
    "emoji-extractor.gemspec",
    "lib/emoji-extractor.rb",
    "test/helper.rb",
    "test/test_emoji-extractor.rb"
  ]
  s.homepage = "http://github.com/andoriyu/emoji-extractor-cli"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "extracts high-resolution emoji pngs from ttf"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

